version: "3.4"

# 重用的代码模板
# 模板的定义必须以 x- 开头
x-logging:
	# 以 & 开头的字符串为模板命名
	# 以 * 加上模板的名称引用模板
  &default-logging
  driver: json-file
  options:
    max-size: "200k"
    max-file: "10"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: WebDockfile
    depends_on:
      - mysql
    user: root
    tty: true
  redis:
    container_name: redis
    image: redis:4.0.14
    ports:
      - "6378:6379"
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    command: [                                       #使用 command 可以覆盖容器启动后默认执行的命令
      '--character-set-server=utf8mb4',              #设置数据库表的数据集
      '--collation-server=utf8mb4_unicode_ci',       #设置数据库表的数据集
      '--default-time-zone=+8:00'                    #设置mysql数据库的 时区问题！！！！ 而不是设置容器的时区问题！！！！
    ]
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: swapping                             #设置初始的数据库名
      MYSQL_ROOT_PASSWORD: oracle                        #设置root连接密码
      MYSQL_ROOT_HOST: '%'
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.190-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'
    #容器用户=root
    user: root
    #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    # 以 * 加上模板的名称引用模板     使用全局自定义模板
    logging: *default-logging
